-- Importación completa del catálogo SEO de Novatec Energy.
-- Ejecutar en la base de datos de producción indicada antes de iniciar la transacción.
USE `u543705487_novatec`;
SET NAMES utf8mb4;
START TRANSACTION;

-- Reinicio exclusivo del catálogo. No elimina archivos físicos ni datos administrativos.
DELETE FROM `products_files`;
DELETE FROM `productos`;
DELETE FROM `subcategory`;
DELETE FROM `category`;

INSERT INTO `category` (`category`, `slug`) VALUES
('Termas solares', 'termas-solares'),
('Paneles solares', 'paneles-solares'),
('Inversores solares', 'inversores-solares'),
('Controladores de carga solar', 'controladores-solares'),
('Baterías para sistemas solares', 'baterias-solares');

INSERT INTO `subcategory` (`id_category`, `subcategory`, `slug`)
SELECT c.id, 'Termas solares de tubos al vacío', 'termas-de-tubos-al-vacio' FROM category c WHERE c.slug = 'termas-solares'
UNION ALL
SELECT c.id, 'Paneles solares de 12V', 'paneles-solares-12v' FROM category c WHERE c.slug = 'paneles-solares'
UNION ALL
SELECT c.id, 'Paneles solares de 24V', 'paneles-solares-24v' FROM category c WHERE c.slug = 'paneles-solares'
UNION ALL
SELECT c.id, 'Inversores solares de 12V', 'inversores-12v' FROM category c WHERE c.slug = 'inversores-solares'
UNION ALL
SELECT c.id, 'Inversores solares de 24V', 'inversores-24v' FROM category c WHERE c.slug = 'inversores-solares'
UNION ALL
SELECT c.id, 'Inversores solares de 48V', 'inversores-48v' FROM category c WHERE c.slug = 'inversores-solares'
UNION ALL
SELECT c.id, 'Inversores solares de alta potencia', 'inversores-de-alta-potencia' FROM category c WHERE c.slug = 'inversores-solares'
UNION ALL
SELECT c.id, 'Controladores de carga solar 12V/24V', 'controladores-12v-24v' FROM category c WHERE c.slug = 'controladores-solares'
UNION ALL
SELECT c.id, 'Controladores de carga solar 24V/48V', 'controladores-24v-48v' FROM category c WHERE c.slug = 'controladores-solares'
UNION ALL
SELECT c.id, 'Baterías AGM de 12V', 'baterias-agm-12v' FROM category c WHERE c.slug = 'baterias-solares'
UNION ALL
SELECT c.id, 'Baterías GEL de 12V', 'baterias-gel-12v' FROM category c WHERE c.slug = 'baterias-solares'
UNION ALL
SELECT c.id, 'Baterías de litio de 12V', 'baterias-de-litio-12v' FROM category c WHERE c.slug = 'baterias-solares'
UNION ALL
SELECT c.id, 'Baterías de litio de 24V', 'baterias-de-litio-24v' FROM category c WHERE c.slug = 'baterias-solares'
UNION ALL
SELECT c.id, 'Baterías de litio de 48V', 'baterias-de-litio-48v' FROM category c WHERE c.slug = 'baterias-solares';

CREATE TEMPORARY TABLE `_import_productos_novatec` (
  `category_slug` varchar(120) NOT NULL,
  `subcategory_slug` varchar(120) NOT NULL,
  `nombre` varchar(255) NOT NULL,
  `slug` varchar(180) NOT NULL,
  `precio_normal` decimal(10,2) NOT NULL
) ENGINE=MEMORY DEFAULT CHARSET=utf8mb4;

INSERT INTO `_import_productos_novatec`
(`category_slug`, `subcategory_slug`, `nombre`, `slug`, `precio_normal`)
VALUES
('termas-solares', 'termas-de-tubos-al-vacio', 'Terma solar de 8 tubos al vacío', 'terma-solar-de-08-tubos-al-vacio', 1200.00),
('termas-solares', 'termas-de-tubos-al-vacio', 'Terma solar de 10 tubos al vacío', 'terma-solar-de-10-tubos-al-vacio', 1300.00),
('termas-solares', 'termas-de-tubos-al-vacio', 'Terma solar de 12 tubos al vacío', 'terma-solar-de-12-tubos-al-vacio', 1500.00),
('termas-solares', 'termas-de-tubos-al-vacio', 'Terma solar de 15 tubos al vacío', 'terma-solar-de-15-tubos-al-vacio', 1700.00),
('termas-solares', 'termas-de-tubos-al-vacio', 'Terma solar de 18 tubos al vacío', 'terma-solar-de-18-tubos-al-vacio', 1900.00),
('termas-solares', 'termas-de-tubos-al-vacio', 'Terma solar de 20 tubos al vacío', 'terma-solar-de-20-tubos-al-vacio', 2100.00),
('termas-solares', 'termas-de-tubos-al-vacio', 'Terma solar de 25 tubos al vacío', 'terma-solar-de-25-tubos-al-vacio', 2700.00),
('termas-solares', 'termas-de-tubos-al-vacio', 'Terma solar de 30 tubos al vacío', 'terma-solar-de-30-tubos-al-vacio', 3000.00),
('paneles-solares', 'paneles-solares-12v', 'Panel solar 5W 12V', 'panel-solar-5w-12v', 30.00),
('paneles-solares', 'paneles-solares-12v', 'Panel solar 10W 12V', 'panel-solar-10w-12v', 40.00),
('paneles-solares', 'paneles-solares-12v', 'Panel solar 20W 12V', 'panel-solar-20w-12v', 70.00),
('paneles-solares', 'paneles-solares-12v', 'Panel solar 35W 12V', 'panel-solar-35w-12v', 90.00),
('paneles-solares', 'paneles-solares-12v', 'Panel solar 55W 12V', 'panel-solar-55w-12v', 120.00),
('paneles-solares', 'paneles-solares-12v', 'Panel solar 80W 12V', 'panel-solar-80w-12v', 160.00),
('paneles-solares', 'paneles-solares-12v', 'Panel solar 110W 12V', 'panel-solar-110w-12v', 210.00),
('paneles-solares', 'paneles-solares-12v', 'Panel solar 135W 12V', 'panel-solar-135w-12v', 300.00),
('paneles-solares', 'paneles-solares-12v', 'Panel solar 170W 12V', 'panel-solar-170w-12v', 350.00),
('paneles-solares', 'paneles-solares-12v', 'Panel solar 225W 12V', 'panel-solar-225w-12v', 225.00),
('paneles-solares', 'paneles-solares-24v', 'Panel solar 280W 24V', 'panel-solar-280w-24v', 450.00),
('paneles-solares', 'paneles-solares-24v', 'Panel solar 380W 24V', 'panel-solar-380w-24v', 500.00),
('paneles-solares', 'paneles-solares-24v', 'Panel solar 450W 24V', 'panel-solar-450w-24v', 550.00),
('paneles-solares', 'paneles-solares-24v', 'Panel solar 550W 24V', 'panel-solar-550w-24v', 600.00),
('paneles-solares', 'paneles-solares-24v', 'Panel solar 650W 24V', 'panel-solar-650w-24v', 650.00),
('paneles-solares', 'paneles-solares-24v', 'Panel solar 720W 24V', 'panel-solar-720w-24v', 700.00),
('inversores-solares', 'inversores-12v', 'Inversor solar MUST 1000W 12V 50A MPPT', 'inversor-solar-must-1000w-12v-50a-mppt', 900.00),
('inversores-solares', 'inversores-24v', 'Inversor solar MUST 2000W 24V 60A MPPT', 'inversor-solar-must-2000w-24v-60a-mppt', 1100.00),
('inversores-solares', 'inversores-24v', 'Inversor solar MUST 3000W 24V 60A MPPT', 'inversor-solar-must-3000w-24v-60a-mppt', 1300.00),
('inversores-solares', 'inversores-48v', 'Inversor solar MUST 4000W 48V 80A MPPT', 'inversor-solar-must-4000w-48v-80a-mppt', 2000.00),
('inversores-solares', 'inversores-48v', 'Inversor solar MUST 5000W 48V 80A MPPT', 'inversor-solar-must-5000w-48v-80a-mppt', 2300.00),
('inversores-solares', 'inversores-de-alta-potencia', 'Inversor solar MUST 7000W', 'inversor-solar-must-7000w', 0.00),
('inversores-solares', 'inversores-de-alta-potencia', 'Inversor solar MUST 9000W', 'inversor-solar-must-9000w', 0.00),
('inversores-solares', 'inversores-de-alta-potencia', 'Inversor solar MUST 10000W', 'inversor-solar-must-10000w', 0.00),
('inversores-solares', 'inversores-de-alta-potencia', 'Inversor solar MUST 12000W', 'inversor-solar-must-12000w', 0.00),
('controladores-solares', 'controladores-12v-24v', 'Controlador solar 10A 12V/24V', 'controlador-solar-10a-12v-24v', 70.00),
('controladores-solares', 'controladores-12v-24v', 'Controlador solar 20A 12V/24V', 'controlador-solar-20a-12v-24v', 80.00),
('controladores-solares', 'controladores-12v-24v', 'Controlador solar 30A 12V/24V', 'controlador-solar-30a-12v-24v', 120.00),
('controladores-solares', 'controladores-12v-24v', 'Controlador solar 40A 12V/24V', 'controlador-solar-40a-12v-24v', 160.00),
('controladores-solares', 'controladores-24v-48v', 'Controlador solar 60A 24V/48V', 'controlador-solar-60a-24v-48v', 200.00),
('baterias-solares', 'baterias-agm-12v', 'Batería solar Leoch AGM 12V 7Ah', 'bateria-solar-leoch-agm-12v-07ah', 40.00),
('baterias-solares', 'baterias-agm-12v', 'Batería solar Leoch AGM 12V 12Ah', 'bateria-solar-leoch-agm-12v-12ah', 75.00),
('baterias-solares', 'baterias-agm-12v', 'Batería solar Leoch AGM 12V 18Ah', 'bateria-solar-leoch-agm-12v-18ah', 110.00),
('baterias-solares', 'baterias-agm-12v', 'Batería solar Leoch AGM 12V 33Ah', 'bateria-solar-leoch-agm-12v-33ah', 220.00),
('baterias-solares', 'baterias-agm-12v', 'Batería solar Leoch AGM 12V 65Ah', 'bateria-solar-leoch-agm-12v-65ah', 420.00),
('baterias-solares', 'baterias-gel-12v', 'Batería solar Leoch GEL 12V 50Ah', 'bateria-solar-leoch-gel-12v-50ah', 400.00),
('baterias-solares', 'baterias-gel-12v', 'Batería solar Leoch GEL 12V 100Ah', 'bateria-solar-leoch-gel-12v-100ah', 600.00),
('baterias-solares', 'baterias-gel-12v', 'Batería solar Leoch GEL 12V 150Ah', 'bateria-solar-leoch-gel-12v-150ah', 950.00),
('baterias-solares', 'baterias-gel-12v', 'Batería solar Leoch GEL 12V 200Ah', 'bateria-solar-leoch-gel-12v-200ah', 1100.00),
('baterias-solares', 'baterias-gel-12v', 'Batería solar Leoch GEL 12V 250Ah', 'bateria-solar-leoch-gel-12v-250ah', 1350.00),
('baterias-solares', 'baterias-de-litio-12v', 'Batería solar Leoch de litio 12V 100Ah', 'bateria-solar-leoch-de-litio-12v-100ah', 900.00),
('baterias-solares', 'baterias-de-litio-12v', 'Batería solar Leoch de litio 12V 150Ah', 'bateria-solar-leoch-de-litio-12v-150ah', 1300.00),
('baterias-solares', 'baterias-de-litio-12v', 'Batería solar Leoch de litio 12V 200Ah', 'bateria-solar-leoch-de-litio-12v-200ah', 1600.00),
('baterias-solares', 'baterias-de-litio-24v', 'Batería solar Leoch de litio 24V 100Ah', 'bateria-solar-leoch-de-litio-24v-100ah', 1700.00),
('baterias-solares', 'baterias-de-litio-24v', 'Batería solar Leoch de litio 24V 150Ah', 'bateria-solar-leoch-de-litio-24v-150ah', 2100.00),
('baterias-solares', 'baterias-de-litio-24v', 'Batería solar Leoch de litio 24V 200Ah', 'bateria-solar-leoch-de-litio-24v-200ah', 2500.00),
('baterias-solares', 'baterias-de-litio-48v', 'Batería solar Leoch de litio 48V 100Ah', 'bateria-solar-leoch-de-litio-48v-100ah', 3000.00),
('baterias-solares', 'baterias-de-litio-48v', 'Batería solar Leoch de litio 48V 150Ah', 'bateria-solar-leoch-de-litio-48v-150ah', 4000.00),
('baterias-solares', 'baterias-de-litio-48v', 'Batería solar Leoch de litio 48V 200Ah', 'bateria-solar-leoch-de-litio-48v-200ah', 5000.00);

INSERT INTO `productos`
(`nombre`, `slug`, `descripcion`, `breve_descripcion`, `precio_normal`, `precio_rebajado`, `cantidad`, `imagen`, `id_categoria`, `id_subcategory`)
SELECT
  t.`nombre`,
  t.`slug`,
  CONCAT(
    '<p>', t.`nombre`, '.</p><h3>Datos del producto</h3>',
    '<p>',
    CASE
      WHEN t.`category_slug` = 'termas-solares' THEN 'Terma solar de tubos al vacío para calentamiento de agua. La cantidad de tubos se indica en el nombre del modelo.'
      WHEN t.`category_slug` = 'paneles-solares' THEN 'Panel solar identificado por la potencia y el voltaje nominales indicados en el nombre del modelo.'
      WHEN t.`category_slug` = 'inversores-solares' THEN 'Inversor solar identificado por la potencia, el voltaje y, cuando figura en el nombre, la corriente y el controlador MPPT.'
      WHEN t.`category_slug` = 'controladores-solares' THEN 'Controlador de carga solar identificado por la corriente y el rango de voltaje indicados en el nombre del modelo.'
      ELSE 'Batería para sistemas solares identificada por su marca, tipo, voltaje y capacidad nominales.'
    END,
    '</p><ul><li>Categoría: ', c.`category`, '</li><li>Subcategoría: ', s.`subcategory`, '</li></ul>',
    '<p>Solicita asesoría técnica y cotización por WhatsApp a Novatec Energy en Puno.</p>'
  ),
  CONCAT(t.`nombre`, '. Solicita cotización y asesoría técnica en Puno por WhatsApp.'),
  t.`precio_normal`,
  0.00,
  0,
  NULL,
  c.`id`,
  s.`id`
FROM `_import_productos_novatec` t
INNER JOIN `category` c ON c.`slug` = t.`category_slug`
INNER JOIN `subcategory` s ON s.`slug` = t.`subcategory_slug` AND s.`id_category` = c.`id`;

CREATE TEMPORARY TABLE `_import_descripciones_seo_novatec` (
  `slug` varchar(180) NOT NULL,
  `descripcion` text NOT NULL,
  `breve_descripcion` varchar(400) NOT NULL,
  PRIMARY KEY (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `_import_descripciones_seo_novatec`
(`slug`, `descripcion`, `breve_descripcion`)
VALUES
('terma-solar-de-08-tubos-al-vacio', '<h3>Características del producto</h3><p>La Terma solar de 08 tubos al vacío aprovecha la energía solar para el calentamiento de agua.</p><p>Es una opción recomendada para viviendas pequeñas, puntos de consumo moderado y usuarios que buscan reducir el uso de electricidad o gas para calentar agua.</p><ul><li>Tipo: terma solar</li><li>Tecnología: tubos al vacío</li><li>Cantidad de tubos: 08</li><li>Aplicación: agua caliente sanitaria con energía solar</li></ul><p>Novatec Energy brinda asesoría para elegir la capacidad adecuada según cantidad de usuarios, consumo diario y condiciones de instalación.</p>', 'Terma solar de 08 tubos al vacío para calentamiento de agua con energía solar, recomendado para viviendas pequeñas, puntos de consumo moderado y usuarios que buscan reducir el uso de electricidad o gas para calentar agua.'),
('terma-solar-de-10-tubos-al-vacio', '<h3>Características del producto</h3><p>La Terma solar de 10 tubos al vacío aprovecha la energía solar para el calentamiento de agua.</p><p>Es una opción recomendada para viviendas pequeñas, puntos de consumo moderado y usuarios que buscan reducir el uso de electricidad o gas para calentar agua.</p><ul><li>Tipo: terma solar</li><li>Tecnología: tubos al vacío</li><li>Cantidad de tubos: 10</li><li>Aplicación: agua caliente sanitaria con energía solar</li></ul><p>Novatec Energy brinda asesoría para elegir la capacidad adecuada según cantidad de usuarios, consumo diario y condiciones de instalación.</p>', 'Terma solar de 10 tubos al vacío para calentamiento de agua con energía solar, recomendado para viviendas pequeñas, puntos de consumo moderado y usuarios que buscan reducir el uso de electricidad o gas para calentar agua.'),
('terma-solar-de-12-tubos-al-vacio', '<h3>Características del producto</h3><p>La Terma solar de 12 tubos al vacío aprovecha la energía solar para el calentamiento de agua.</p><p>Es una opción recomendada para viviendas pequeñas, puntos de consumo moderado y usuarios que buscan reducir el uso de electricidad o gas para calentar agua.</p><ul><li>Tipo: terma solar</li><li>Tecnología: tubos al vacío</li><li>Cantidad de tubos: 12</li><li>Aplicación: agua caliente sanitaria con energía solar</li></ul><p>Novatec Energy brinda asesoría para elegir la capacidad adecuada según cantidad de usuarios, consumo diario y condiciones de instalación.</p>', 'Terma solar de 12 tubos al vacío para calentamiento de agua con energía solar, recomendado para viviendas pequeñas, puntos de consumo moderado y usuarios que buscan reducir el uso de electricidad o gas para calentar agua.'),
('terma-solar-de-15-tubos-al-vacio', '<h3>Características del producto</h3><p>La Terma solar de 15 tubos al vacío aprovecha la energía solar para el calentamiento de agua.</p><p>Es una opción recomendada para viviendas familiares, negocios pequeños y espacios con consumo medio de agua caliente.</p><ul><li>Tipo: terma solar</li><li>Tecnología: tubos al vacío</li><li>Cantidad de tubos: 15</li><li>Aplicación: agua caliente sanitaria con energía solar</li></ul><p>Novatec Energy brinda asesoría para elegir la capacidad adecuada según cantidad de usuarios, consumo diario y condiciones de instalación.</p>', 'Terma solar de 15 tubos al vacío para calentamiento de agua con energía solar, recomendado para viviendas familiares, negocios pequeños y espacios con consumo medio de agua caliente.'),
('terma-solar-de-18-tubos-al-vacio', '<h3>Características del producto</h3><p>La Terma solar de 18 tubos al vacío aprovecha la energía solar para el calentamiento de agua.</p><p>Es una opción recomendada para viviendas familiares, negocios pequeños y espacios con consumo medio de agua caliente.</p><ul><li>Tipo: terma solar</li><li>Tecnología: tubos al vacío</li><li>Cantidad de tubos: 18</li><li>Aplicación: agua caliente sanitaria con energía solar</li></ul><p>Novatec Energy brinda asesoría para elegir la capacidad adecuada según cantidad de usuarios, consumo diario y condiciones de instalación.</p>', 'Terma solar de 18 tubos al vacío para calentamiento de agua con energía solar, recomendado para viviendas familiares, negocios pequeños y espacios con consumo medio de agua caliente.'),
('terma-solar-de-20-tubos-al-vacio', '<h3>Características del producto</h3><p>La Terma solar de 20 tubos al vacío aprovecha la energía solar para el calentamiento de agua.</p><p>Es una opción recomendada para viviendas familiares, negocios pequeños y espacios con consumo medio de agua caliente.</p><ul><li>Tipo: terma solar</li><li>Tecnología: tubos al vacío</li><li>Cantidad de tubos: 20</li><li>Aplicación: agua caliente sanitaria con energía solar</li></ul><p>Novatec Energy brinda asesoría para elegir la capacidad adecuada según cantidad de usuarios, consumo diario y condiciones de instalación.</p>', 'Terma solar de 20 tubos al vacío para calentamiento de agua con energía solar, recomendado para viviendas familiares, negocios pequeños y espacios con consumo medio de agua caliente.'),
('terma-solar-de-25-tubos-al-vacio', '<h3>Características del producto</h3><p>La Terma solar de 25 tubos al vacío aprovecha la energía solar para el calentamiento de agua.</p><p>Es una opción recomendada para viviendas con mayor demanda, hospedajes, negocios o instalaciones que requieren más disponibilidad de agua caliente.</p><ul><li>Tipo: terma solar</li><li>Tecnología: tubos al vacío</li><li>Cantidad de tubos: 25</li><li>Aplicación: agua caliente sanitaria con energía solar</li></ul><p>Novatec Energy brinda asesoría para elegir la capacidad adecuada según cantidad de usuarios, consumo diario y condiciones de instalación.</p>', 'Terma solar de 25 tubos al vacío para calentamiento de agua con energía solar, recomendado para viviendas con mayor demanda, hospedajes, negocios o instalaciones que requieren más disponibilidad de agua caliente.'),
('terma-solar-de-30-tubos-al-vacio', '<h3>Características del producto</h3><p>La Terma solar de 30 tubos al vacío aprovecha la energía solar para el calentamiento de agua.</p><p>Es una opción recomendada para viviendas con mayor demanda, hospedajes, negocios o instalaciones que requieren más disponibilidad de agua caliente.</p><ul><li>Tipo: terma solar</li><li>Tecnología: tubos al vacío</li><li>Cantidad de tubos: 30</li><li>Aplicación: agua caliente sanitaria con energía solar</li></ul><p>Novatec Energy brinda asesoría para elegir la capacidad adecuada según cantidad de usuarios, consumo diario y condiciones de instalación.</p>', 'Terma solar de 30 tubos al vacío para calentamiento de agua con energía solar, recomendado para viviendas con mayor demanda, hospedajes, negocios o instalaciones que requieren más disponibilidad de agua caliente.'),
('panel-solar-5w-12v', '<h3>Características del producto</h3><p>El Panel solar 5W 12V es una alternativa práctica para aprovechar la energía solar en iluminación básica, pequeños consumos, cercos eléctricos, cámaras, carga de baterías pequeñas y aplicaciones solares puntuales.</p><p>Este panel solar requiere dimensionamiento técnico junto con los demás componentes del sistema solar.</p><ul><li>Potencia: 5W</li><li>Voltaje nominal: 12V</li><li>Categoría: Paneles solares</li><li>Uso recomendado: iluminación básica, pequeños consumos, cercos eléctricos, cámaras, carga de baterías pequeñas y aplicaciones solares puntuales</li></ul><p>En Novatec Energy brindamos asesoría para elegir el panel adecuado según consumo, autonomía requerida y tipo de sistema solar.</p>', 'Panel solar 5W 12V para iluminación básica, pequeños consumos, cercos eléctricos, cámaras, carga de baterías pequeñas y aplicaciones solares puntuales, ideal para proyectos de energía solar y carga de baterías.'),
('panel-solar-10w-12v', '<h3>Características del producto</h3><p>El Panel solar 10W 12V es una alternativa práctica para aprovechar la energía solar en iluminación básica, pequeños consumos, cercos eléctricos, cámaras, carga de baterías pequeñas y aplicaciones solares puntuales.</p><p>Este panel solar requiere dimensionamiento técnico junto con los demás componentes del sistema solar.</p><ul><li>Potencia: 10W</li><li>Voltaje nominal: 12V</li><li>Categoría: Paneles solares</li><li>Uso recomendado: iluminación básica, pequeños consumos, cercos eléctricos, cámaras, carga de baterías pequeñas y aplicaciones solares puntuales</li></ul><p>En Novatec Energy brindamos asesoría para elegir el panel adecuado según consumo, autonomía requerida y tipo de sistema solar.</p>', 'Panel solar 10W 12V para iluminación básica, pequeños consumos, cercos eléctricos, cámaras, carga de baterías pequeñas y aplicaciones solares puntuales, ideal para proyectos de energía solar y carga de baterías.'),
('panel-solar-20w-12v', '<h3>Características del producto</h3><p>El Panel solar 20W 12V es una alternativa práctica para aprovechar la energía solar en iluminación básica, pequeños consumos, cercos eléctricos, cámaras, carga de baterías pequeñas y aplicaciones solares puntuales.</p><p>Este panel solar requiere dimensionamiento técnico junto con los demás componentes del sistema solar.</p><ul><li>Potencia: 20W</li><li>Voltaje nominal: 12V</li><li>Categoría: Paneles solares</li><li>Uso recomendado: iluminación básica, pequeños consumos, cercos eléctricos, cámaras, carga de baterías pequeñas y aplicaciones solares puntuales</li></ul><p>En Novatec Energy brindamos asesoría para elegir el panel adecuado según consumo, autonomía requerida y tipo de sistema solar.</p>', 'Panel solar 20W 12V para iluminación básica, pequeños consumos, cercos eléctricos, cámaras, carga de baterías pequeñas y aplicaciones solares puntuales, ideal para proyectos de energía solar y carga de baterías.'),
('panel-solar-35w-12v', '<h3>Características del producto</h3><p>El Panel solar 35W 12V es una alternativa práctica para aprovechar la energía solar en iluminación básica, pequeños consumos, cercos eléctricos, cámaras, carga de baterías pequeñas y aplicaciones solares puntuales.</p><p>Este panel solar requiere dimensionamiento técnico junto con los demás componentes del sistema solar.</p><ul><li>Potencia: 35W</li><li>Voltaje nominal: 12V</li><li>Categoría: Paneles solares</li><li>Uso recomendado: iluminación básica, pequeños consumos, cercos eléctricos, cámaras, carga de baterías pequeñas y aplicaciones solares puntuales</li></ul><p>En Novatec Energy brindamos asesoría para elegir el panel adecuado según consumo, autonomía requerida y tipo de sistema solar.</p>', 'Panel solar 35W 12V para iluminación básica, pequeños consumos, cercos eléctricos, cámaras, carga de baterías pequeñas y aplicaciones solares puntuales, ideal para proyectos de energía solar y carga de baterías.'),
('panel-solar-55w-12v', '<h3>Características del producto</h3><p>El Panel solar 55W 12V es una alternativa práctica para aprovechar la energía solar en iluminación básica, pequeños consumos, cercos eléctricos, cámaras, carga de baterías pequeñas y aplicaciones solares puntuales.</p><p>Este panel solar requiere dimensionamiento técnico junto con los demás componentes del sistema solar.</p><ul><li>Potencia: 55W</li><li>Voltaje nominal: 12V</li><li>Categoría: Paneles solares</li><li>Uso recomendado: iluminación básica, pequeños consumos, cercos eléctricos, cámaras, carga de baterías pequeñas y aplicaciones solares puntuales</li></ul><p>En Novatec Energy brindamos asesoría para elegir el panel adecuado según consumo, autonomía requerida y tipo de sistema solar.</p>', 'Panel solar 55W 12V para iluminación básica, pequeños consumos, cercos eléctricos, cámaras, carga de baterías pequeñas y aplicaciones solares puntuales, ideal para proyectos de energía solar y carga de baterías.'),
('panel-solar-80w-12v', '<h3>Características del producto</h3><p>El Panel solar 80W 12V es una alternativa práctica para aprovechar la energía solar en sistemas solares pequeños o medianos, carga de baterías, iluminación, equipos de bajo consumo y soluciones aisladas.</p><p>Este panel solar requiere dimensionamiento técnico junto con los demás componentes del sistema solar.</p><ul><li>Potencia: 80W</li><li>Voltaje nominal: 12V</li><li>Categoría: Paneles solares</li><li>Uso recomendado: sistemas solares pequeños o medianos, carga de baterías, iluminación, equipos de bajo consumo y soluciones aisladas</li></ul><p>En Novatec Energy brindamos asesoría para elegir el panel adecuado según consumo, autonomía requerida y tipo de sistema solar.</p>', 'Panel solar 80W 12V para sistemas solares pequeños o medianos, carga de baterías, iluminación, equipos de bajo consumo y soluciones aisladas, ideal para proyectos de energía solar y carga de baterías.'),
('panel-solar-110w-12v', '<h3>Características del producto</h3><p>El Panel solar 110W 12V es una alternativa práctica para aprovechar la energía solar en sistemas solares pequeños o medianos, carga de baterías, iluminación, equipos de bajo consumo y soluciones aisladas.</p><p>Este panel solar requiere dimensionamiento técnico junto con los demás componentes del sistema solar.</p><ul><li>Potencia: 110W</li><li>Voltaje nominal: 12V</li><li>Categoría: Paneles solares</li><li>Uso recomendado: sistemas solares pequeños o medianos, carga de baterías, iluminación, equipos de bajo consumo y soluciones aisladas</li></ul><p>En Novatec Energy brindamos asesoría para elegir el panel adecuado según consumo, autonomía requerida y tipo de sistema solar.</p>', 'Panel solar 110W 12V para sistemas solares pequeños o medianos, carga de baterías, iluminación, equipos de bajo consumo y soluciones aisladas, ideal para proyectos de energía solar y carga de baterías.'),
('panel-solar-135w-12v', '<h3>Características del producto</h3><p>El Panel solar 135W 12V es una alternativa práctica para aprovechar la energía solar en sistemas solares pequeños o medianos, carga de baterías, iluminación, equipos de bajo consumo y soluciones aisladas.</p><p>Este panel solar requiere dimensionamiento técnico junto con los demás componentes del sistema solar.</p><ul><li>Potencia: 135W</li><li>Voltaje nominal: 12V</li><li>Categoría: Paneles solares</li><li>Uso recomendado: sistemas solares pequeños o medianos, carga de baterías, iluminación, equipos de bajo consumo y soluciones aisladas</li></ul><p>En Novatec Energy brindamos asesoría para elegir el panel adecuado según consumo, autonomía requerida y tipo de sistema solar.</p>', 'Panel solar 135W 12V para sistemas solares pequeños o medianos, carga de baterías, iluminación, equipos de bajo consumo y soluciones aisladas, ideal para proyectos de energía solar y carga de baterías.'),
('panel-solar-170w-12v', '<h3>Características del producto</h3><p>El Panel solar 170W 12V es una alternativa práctica para aprovechar la energía solar en sistemas solares pequeños o medianos, carga de baterías, iluminación, equipos de bajo consumo y soluciones aisladas.</p><p>Este panel solar requiere dimensionamiento técnico junto con los demás componentes del sistema solar.</p><ul><li>Potencia: 170W</li><li>Voltaje nominal: 12V</li><li>Categoría: Paneles solares</li><li>Uso recomendado: sistemas solares pequeños o medianos, carga de baterías, iluminación, equipos de bajo consumo y soluciones aisladas</li></ul><p>En Novatec Energy brindamos asesoría para elegir el panel adecuado según consumo, autonomía requerida y tipo de sistema solar.</p>', 'Panel solar 170W 12V para sistemas solares pequeños o medianos, carga de baterías, iluminación, equipos de bajo consumo y soluciones aisladas, ideal para proyectos de energía solar y carga de baterías.'),
('panel-solar-225w-12v', '<h3>Características del producto</h3><p>El Panel solar 225W 12V es una alternativa práctica para aprovechar la energía solar en sistemas solares pequeños o medianos, carga de baterías, iluminación, equipos de bajo consumo y soluciones aisladas.</p><p>Este panel solar requiere dimensionamiento técnico junto con los demás componentes del sistema solar.</p><ul><li>Potencia: 225W</li><li>Voltaje nominal: 12V</li><li>Categoría: Paneles solares</li><li>Uso recomendado: sistemas solares pequeños o medianos, carga de baterías, iluminación, equipos de bajo consumo y soluciones aisladas</li></ul><p>En Novatec Energy brindamos asesoría para elegir el panel adecuado según consumo, autonomía requerida y tipo de sistema solar.</p>', 'Panel solar 225W 12V para sistemas solares pequeños o medianos, carga de baterías, iluminación, equipos de bajo consumo y soluciones aisladas, ideal para proyectos de energía solar y carga de baterías.'),
('panel-solar-280w-24v', '<h3>Características del producto</h3><p>El Panel solar 280W 24V es una alternativa práctica para aprovechar la energía solar en sistemas fotovoltaicos domiciliarios, carga de bancos de baterías y proyectos solares de mayor demanda.</p><p>Este panel solar requiere dimensionamiento técnico junto con los demás componentes del sistema solar.</p><ul><li>Potencia: 280W</li><li>Voltaje nominal: 24V</li><li>Categoría: Paneles solares</li><li>Uso recomendado: sistemas fotovoltaicos domiciliarios, carga de bancos de baterías y proyectos solares de mayor demanda</li></ul><p>En Novatec Energy brindamos asesoría para elegir el panel adecuado según consumo, autonomía requerida y tipo de sistema solar.</p>', 'Panel solar 280W 24V para sistemas fotovoltaicos domiciliarios, carga de bancos de baterías y proyectos solares de mayor demanda, ideal para proyectos de energía solar y carga de baterías.'),
('panel-solar-380w-24v', '<h3>Características del producto</h3><p>El Panel solar 380W 24V es una alternativa práctica para aprovechar la energía solar en sistemas fotovoltaicos domiciliarios, carga de bancos de baterías y proyectos solares de mayor demanda.</p><p>Este panel solar requiere dimensionamiento técnico junto con los demás componentes del sistema solar.</p><ul><li>Potencia: 380W</li><li>Voltaje nominal: 24V</li><li>Categoría: Paneles solares</li><li>Uso recomendado: sistemas fotovoltaicos domiciliarios, carga de bancos de baterías y proyectos solares de mayor demanda</li></ul><p>En Novatec Energy brindamos asesoría para elegir el panel adecuado según consumo, autonomía requerida y tipo de sistema solar.</p>', 'Panel solar 380W 24V para sistemas fotovoltaicos domiciliarios, carga de bancos de baterías y proyectos solares de mayor demanda, ideal para proyectos de energía solar y carga de baterías.'),
('panel-solar-450w-24v', '<h3>Características del producto</h3><p>El Panel solar 450W 24V es una alternativa práctica para aprovechar la energía solar en sistemas fotovoltaicos domiciliarios, carga de bancos de baterías y proyectos solares de mayor demanda.</p><p>Este panel solar requiere dimensionamiento técnico junto con los demás componentes del sistema solar.</p><ul><li>Potencia: 450W</li><li>Voltaje nominal: 24V</li><li>Categoría: Paneles solares</li><li>Uso recomendado: sistemas fotovoltaicos domiciliarios, carga de bancos de baterías y proyectos solares de mayor demanda</li></ul><p>En Novatec Energy brindamos asesoría para elegir el panel adecuado según consumo, autonomía requerida y tipo de sistema solar.</p>', 'Panel solar 450W 24V para sistemas fotovoltaicos domiciliarios, carga de bancos de baterías y proyectos solares de mayor demanda, ideal para proyectos de energía solar y carga de baterías.'),
('panel-solar-550w-24v', '<h3>Características del producto</h3><p>El Panel solar 550W 24V es una alternativa práctica para aprovechar la energía solar en instalaciones solares de alta potencia, sistemas domiciliarios o comerciales y proyectos que requieren mayor generación energética.</p><p>Este panel solar requiere dimensionamiento técnico junto con los demás componentes del sistema solar.</p><ul><li>Potencia: 550W</li><li>Voltaje nominal: 24V</li><li>Categoría: Paneles solares</li><li>Uso recomendado: instalaciones solares de alta potencia, sistemas domiciliarios o comerciales y proyectos que requieren mayor generación energética</li></ul><p>En Novatec Energy brindamos asesoría para elegir el panel adecuado según consumo, autonomía requerida y tipo de sistema solar.</p>', 'Panel solar 550W 24V para instalaciones solares de alta potencia, sistemas domiciliarios o comerciales y proyectos que requieren mayor generación energética, ideal para proyectos de energía solar y carga de baterías.'),
('panel-solar-650w-24v', '<h3>Características del producto</h3><p>El Panel solar 650W 24V es una alternativa práctica para aprovechar la energía solar en instalaciones solares de alta potencia, sistemas domiciliarios o comerciales y proyectos que requieren mayor generación energética.</p><p>Este panel solar requiere dimensionamiento técnico junto con los demás componentes del sistema solar.</p><ul><li>Potencia: 650W</li><li>Voltaje nominal: 24V</li><li>Categoría: Paneles solares</li><li>Uso recomendado: instalaciones solares de alta potencia, sistemas domiciliarios o comerciales y proyectos que requieren mayor generación energética</li></ul><p>En Novatec Energy brindamos asesoría para elegir el panel adecuado según consumo, autonomía requerida y tipo de sistema solar.</p>', 'Panel solar 650W 24V para instalaciones solares de alta potencia, sistemas domiciliarios o comerciales y proyectos que requieren mayor generación energética, ideal para proyectos de energía solar y carga de baterías.'),
('panel-solar-720w-24v', '<h3>Características del producto</h3><p>El Panel solar 720W 24V es una alternativa práctica para aprovechar la energía solar en instalaciones solares de alta potencia, sistemas domiciliarios o comerciales y proyectos que requieren mayor generación energética.</p><p>Este panel solar requiere dimensionamiento técnico junto con los demás componentes del sistema solar.</p><ul><li>Potencia: 720W</li><li>Voltaje nominal: 24V</li><li>Categoría: Paneles solares</li><li>Uso recomendado: instalaciones solares de alta potencia, sistemas domiciliarios o comerciales y proyectos que requieren mayor generación energética</li></ul><p>En Novatec Energy brindamos asesoría para elegir el panel adecuado según consumo, autonomía requerida y tipo de sistema solar.</p>', 'Panel solar 720W 24V para instalaciones solares de alta potencia, sistemas domiciliarios o comerciales y proyectos que requieren mayor generación energética, ideal para proyectos de energía solar y carga de baterías.'),
('inversor-solar-must-1000w-12v-50a-mppt', '<h3>Características del producto</h3><p>El Inversor solar MUST 1000W 12V 50A MPPT permite convertir la energía almacenada en baterías para alimentar equipos eléctricos en sistemas solares fotovoltaicos.</p><p>Es recomendado para sistemas pequeños con baterías, respaldo básico e instalaciones solares de baja demanda.</p><p>Antes de instalar un inversor, es importante validar la compatibilidad con el banco de baterías, los paneles solares y la demanda total de consumo.</p><ul><li>Potencia: 1000W</li><li>Voltaje de trabajo: 12V</li><li>Corriente de carga: 50A</li><li>Tecnología: MPPT</li><li>Marca: MUST</li><li>Aplicación: conversión de energía para sistemas solares con baterías</li></ul><p>Novatec Energy te ayuda a dimensionar el inversor adecuado para tu instalación y necesidades de respaldo energético.</p>', 'Inversor solar MUST 1000W 12V 50A MPPT para sistemas pequeños con baterías, respaldo básico e instalaciones solares de baja demanda, compatible con sistemas fotovoltaicos con baterías.'),
('inversor-solar-must-2000w-24v-60a-mppt', '<h3>Características del producto</h3><p>El Inversor solar MUST 2000W 24V 60A MPPT permite convertir la energía almacenada en baterías para alimentar equipos eléctricos en sistemas solares fotovoltaicos.</p><p>Es recomendado para sistemas solares medianos, viviendas, equipos de consumo moderado y respaldo energético.</p><p>Antes de instalar un inversor, es importante validar la compatibilidad con el banco de baterías, los paneles solares y la demanda total de consumo.</p><ul><li>Potencia: 2000W</li><li>Voltaje de trabajo: 24V</li><li>Corriente de carga: 60A</li><li>Tecnología: MPPT</li><li>Marca: MUST</li><li>Aplicación: conversión de energía para sistemas solares con baterías</li></ul><p>Novatec Energy te ayuda a dimensionar el inversor adecuado para tu instalación y necesidades de respaldo energético.</p>', 'Inversor solar MUST 2000W 24V 60A MPPT para sistemas solares medianos, viviendas, equipos de consumo moderado y respaldo energético, compatible con sistemas fotovoltaicos con baterías.'),
('inversor-solar-must-3000w-24v-60a-mppt', '<h3>Características del producto</h3><p>El Inversor solar MUST 3000W 24V 60A MPPT permite convertir la energía almacenada en baterías para alimentar equipos eléctricos en sistemas solares fotovoltaicos.</p><p>Es recomendado para sistemas solares medianos, viviendas, equipos de consumo moderado y respaldo energético.</p><p>Antes de instalar un inversor, es importante validar la compatibilidad con el banco de baterías, los paneles solares y la demanda total de consumo.</p><ul><li>Potencia: 3000W</li><li>Voltaje de trabajo: 24V</li><li>Corriente de carga: 60A</li><li>Tecnología: MPPT</li><li>Marca: MUST</li><li>Aplicación: conversión de energía para sistemas solares con baterías</li></ul><p>Novatec Energy te ayuda a dimensionar el inversor adecuado para tu instalación y necesidades de respaldo energético.</p>', 'Inversor solar MUST 3000W 24V 60A MPPT para sistemas solares medianos, viviendas, equipos de consumo moderado y respaldo energético, compatible con sistemas fotovoltaicos con baterías.'),
('inversor-solar-must-4000w-48v-80a-mppt', '<h3>Características del producto</h3><p>El Inversor solar MUST 4000W 48V 80A MPPT permite convertir la energía almacenada en baterías para alimentar equipos eléctricos en sistemas solares fotovoltaicos.</p><p>Es recomendado para instalaciones solares de mayor capacidad, bancos de baterías y respaldo para múltiples equipos.</p><p>Antes de instalar un inversor, es importante validar la compatibilidad con el banco de baterías, los paneles solares y la demanda total de consumo.</p><ul><li>Potencia: 4000W</li><li>Voltaje de trabajo: 48V</li><li>Corriente de carga: 80A</li><li>Tecnología: MPPT</li><li>Marca: MUST</li><li>Aplicación: conversión de energía para sistemas solares con baterías</li></ul><p>Novatec Energy te ayuda a dimensionar el inversor adecuado para tu instalación y necesidades de respaldo energético.</p>', 'Inversor solar MUST 4000W 48V 80A MPPT para instalaciones solares de mayor capacidad, bancos de baterías y respaldo para múltiples equipos, compatible con sistemas fotovoltaicos con baterías.'),
('inversor-solar-must-5000w-48v-80a-mppt', '<h3>Características del producto</h3><p>El Inversor solar MUST 5000W 48V 80A MPPT permite convertir la energía almacenada en baterías para alimentar equipos eléctricos en sistemas solares fotovoltaicos.</p><p>Es recomendado para instalaciones solares de mayor capacidad, bancos de baterías y respaldo para múltiples equipos.</p><p>Antes de instalar un inversor, es importante validar la compatibilidad con el banco de baterías, los paneles solares y la demanda total de consumo.</p><ul><li>Potencia: 5000W</li><li>Voltaje de trabajo: 48V</li><li>Corriente de carga: 80A</li><li>Tecnología: MPPT</li><li>Marca: MUST</li><li>Aplicación: conversión de energía para sistemas solares con baterías</li></ul><p>Novatec Energy te ayuda a dimensionar el inversor adecuado para tu instalación y necesidades de respaldo energético.</p>', 'Inversor solar MUST 5000W 48V 80A MPPT para instalaciones solares de mayor capacidad, bancos de baterías y respaldo para múltiples equipos, compatible con sistemas fotovoltaicos con baterías.'),
('inversor-solar-must-7000w', '<h3>Características del producto</h3><p>El Inversor solar MUST 7000W permite convertir la energía almacenada en baterías para alimentar equipos eléctricos en sistemas solares fotovoltaicos.</p><p>Es recomendado para proyectos solares de alta demanda que requieren evaluación técnica y cotización personalizada.</p><p>Antes de instalar un inversor, es importante validar la compatibilidad con el banco de baterías, los paneles solares y la demanda total de consumo.</p><ul><li>Potencia: 7000W</li><li>Marca: MUST</li><li>Aplicación: conversión de energía para sistemas solares con baterías</li></ul><p><strong>Precio a consultar.</strong> Solicita una cotización personalizada según la configuración de tu sistema.</p><p>Novatec Energy te ayuda a dimensionar el inversor adecuado para tu instalación y necesidades de respaldo energético.</p>', 'Inversor solar MUST 7000W para proyectos solares de alta demanda que requieren evaluación técnica y cotización personalizada, compatible con sistemas fotovoltaicos con baterías. Producto disponible con precio a consultar.'),
('inversor-solar-must-9000w', '<h3>Características del producto</h3><p>El Inversor solar MUST 9000W permite convertir la energía almacenada en baterías para alimentar equipos eléctricos en sistemas solares fotovoltaicos.</p><p>Es recomendado para proyectos solares de alta demanda que requieren evaluación técnica y cotización personalizada.</p><p>Antes de instalar un inversor, es importante validar la compatibilidad con el banco de baterías, los paneles solares y la demanda total de consumo.</p><ul><li>Potencia: 9000W</li><li>Marca: MUST</li><li>Aplicación: conversión de energía para sistemas solares con baterías</li></ul><p><strong>Precio a consultar.</strong> Solicita una cotización personalizada según la configuración de tu sistema.</p><p>Novatec Energy te ayuda a dimensionar el inversor adecuado para tu instalación y necesidades de respaldo energético.</p>', 'Inversor solar MUST 9000W para proyectos solares de alta demanda que requieren evaluación técnica y cotización personalizada, compatible con sistemas fotovoltaicos con baterías. Producto disponible con precio a consultar.'),
('inversor-solar-must-10000w', '<h3>Características del producto</h3><p>El Inversor solar MUST 10000W permite convertir la energía almacenada en baterías para alimentar equipos eléctricos en sistemas solares fotovoltaicos.</p><p>Es recomendado para proyectos solares de alta demanda que requieren evaluación técnica y cotización personalizada.</p><p>Antes de instalar un inversor, es importante validar la compatibilidad con el banco de baterías, los paneles solares y la demanda total de consumo.</p><ul><li>Potencia: 10000W</li><li>Marca: MUST</li><li>Aplicación: conversión de energía para sistemas solares con baterías</li></ul><p><strong>Precio a consultar.</strong> Solicita una cotización personalizada según la configuración de tu sistema.</p><p>Novatec Energy te ayuda a dimensionar el inversor adecuado para tu instalación y necesidades de respaldo energético.</p>', 'Inversor solar MUST 10000W para proyectos solares de alta demanda que requieren evaluación técnica y cotización personalizada, compatible con sistemas fotovoltaicos con baterías. Producto disponible con precio a consultar.'),
('inversor-solar-must-12000w', '<h3>Características del producto</h3><p>El Inversor solar MUST 12000W permite convertir la energía almacenada en baterías para alimentar equipos eléctricos en sistemas solares fotovoltaicos.</p><p>Es recomendado para proyectos solares de alta demanda que requieren evaluación técnica y cotización personalizada.</p><p>Antes de instalar un inversor, es importante validar la compatibilidad con el banco de baterías, los paneles solares y la demanda total de consumo.</p><ul><li>Potencia: 12000W</li><li>Marca: MUST</li><li>Aplicación: conversión de energía para sistemas solares con baterías</li></ul><p><strong>Precio a consultar.</strong> Solicita una cotización personalizada según la configuración de tu sistema.</p><p>Novatec Energy te ayuda a dimensionar el inversor adecuado para tu instalación y necesidades de respaldo energético.</p>', 'Inversor solar MUST 12000W para proyectos solares de alta demanda que requieren evaluación técnica y cotización personalizada, compatible con sistemas fotovoltaicos con baterías. Producto disponible con precio a consultar.'),
('controlador-solar-10a-12v-24v', '<h3>Características del producto</h3><p>El Controlador solar 10A 12V/24V regula la energía proveniente de los paneles solares hacia las baterías, ayudando a proteger el sistema y mejorar su funcionamiento.</p><p>Es un componente importante para sistemas solares pequeños, paneles de baja potencia y carga de baterías en instalaciones básicas.</p><ul><li>Corriente: 10A</li><li>Voltaje compatible: 12V/24V</li><li>Aplicación: regulación de carga solar</li><li>Uso recomendado: conexión entre paneles solares y baterías</li></ul><p>Novatec Energy brinda asesoría para elegir el controlador adecuado según potencia de paneles, voltaje del sistema y capacidad de baterías.</p>', 'Controlador solar 10A 12V/24V para regular la carga entre paneles solares y baterías en sistemas solares pequeños, paneles de baja potencia y carga de baterías en instalaciones básicas.'),
('controlador-solar-20a-12v-24v', '<h3>Características del producto</h3><p>El Controlador solar 20A 12V/24V regula la energía proveniente de los paneles solares hacia las baterías, ayudando a proteger el sistema y mejorar su funcionamiento.</p><p>Es un componente importante para sistemas solares pequeños, paneles de baja potencia y carga de baterías en instalaciones básicas.</p><ul><li>Corriente: 20A</li><li>Voltaje compatible: 12V/24V</li><li>Aplicación: regulación de carga solar</li><li>Uso recomendado: conexión entre paneles solares y baterías</li></ul><p>Novatec Energy brinda asesoría para elegir el controlador adecuado según potencia de paneles, voltaje del sistema y capacidad de baterías.</p>', 'Controlador solar 20A 12V/24V para regular la carga entre paneles solares y baterías en sistemas solares pequeños, paneles de baja potencia y carga de baterías en instalaciones básicas.'),
('controlador-solar-30a-12v-24v', '<h3>Características del producto</h3><p>El Controlador solar 30A 12V/24V regula la energía proveniente de los paneles solares hacia las baterías, ayudando a proteger el sistema y mejorar su funcionamiento.</p><p>Es un componente importante para sistemas solares medianos que requieren una regulación estable entre paneles y baterías.</p><ul><li>Corriente: 30A</li><li>Voltaje compatible: 12V/24V</li><li>Aplicación: regulación de carga solar</li><li>Uso recomendado: conexión entre paneles solares y baterías</li></ul><p>Novatec Energy brinda asesoría para elegir el controlador adecuado según potencia de paneles, voltaje del sistema y capacidad de baterías.</p>', 'Controlador solar 30A 12V/24V para regular la carga entre paneles solares y baterías en sistemas solares medianos que requieren una regulación estable entre paneles y baterías.'),
('controlador-solar-40a-12v-24v', '<h3>Características del producto</h3><p>El Controlador solar 40A 12V/24V regula la energía proveniente de los paneles solares hacia las baterías, ayudando a proteger el sistema y mejorar su funcionamiento.</p><p>Es un componente importante para sistemas solares medianos que requieren una regulación estable entre paneles y baterías.</p><ul><li>Corriente: 40A</li><li>Voltaje compatible: 12V/24V</li><li>Aplicación: regulación de carga solar</li><li>Uso recomendado: conexión entre paneles solares y baterías</li></ul><p>Novatec Energy brinda asesoría para elegir el controlador adecuado según potencia de paneles, voltaje del sistema y capacidad de baterías.</p>', 'Controlador solar 40A 12V/24V para regular la carga entre paneles solares y baterías en sistemas solares medianos que requieren una regulación estable entre paneles y baterías.'),
('controlador-solar-60a-24v-48v', '<h3>Características del producto</h3><p>El Controlador solar 60A 24V/48V regula la energía proveniente de los paneles solares hacia las baterías, ayudando a proteger el sistema y mejorar su funcionamiento.</p><p>Es un componente importante para sistemas solares de mayor capacidad que trabajan con bancos de baterías y paneles de más potencia.</p><ul><li>Corriente: 60A</li><li>Voltaje compatible: 24V/48V</li><li>Aplicación: regulación de carga solar</li><li>Uso recomendado: conexión entre paneles solares y baterías</li></ul><p>Novatec Energy brinda asesoría para elegir el controlador adecuado según potencia de paneles, voltaje del sistema y capacidad de baterías.</p>', 'Controlador solar 60A 24V/48V para regular la carga entre paneles solares y baterías en sistemas solares de mayor capacidad que trabajan con bancos de baterías y paneles de más potencia.'),
('bateria-solar-leoch-agm-12v-07ah', '<h3>Características del producto</h3><p>La Batería solar Leoch AGM 12V 07Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para respaldo eléctrico, sistemas solares pequeños, alarmas, iluminación y aplicaciones donde se requiere almacenamiento confiable.</p><ul><li>Marca: Leoch</li><li>Tecnología: AGM</li><li>Voltaje: 12V</li><li>Capacidad nominal: 07Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch AGM 12V 07Ah para almacenamiento de energía en respaldo eléctrico, sistemas solares pequeños, alarmas, iluminación y aplicaciones donde se requiere almacenamiento confiable.'),
('bateria-solar-leoch-agm-12v-12ah', '<h3>Características del producto</h3><p>La Batería solar Leoch AGM 12V 12Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para respaldo eléctrico, sistemas solares pequeños, alarmas, iluminación y aplicaciones donde se requiere almacenamiento confiable.</p><ul><li>Marca: Leoch</li><li>Tecnología: AGM</li><li>Voltaje: 12V</li><li>Capacidad nominal: 12Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch AGM 12V 12Ah para almacenamiento de energía en respaldo eléctrico, sistemas solares pequeños, alarmas, iluminación y aplicaciones donde se requiere almacenamiento confiable.'),
('bateria-solar-leoch-agm-12v-18ah', '<h3>Características del producto</h3><p>La Batería solar Leoch AGM 12V 18Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para respaldo eléctrico, sistemas solares pequeños, alarmas, iluminación y aplicaciones donde se requiere almacenamiento confiable.</p><ul><li>Marca: Leoch</li><li>Tecnología: AGM</li><li>Voltaje: 12V</li><li>Capacidad nominal: 18Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch AGM 12V 18Ah para almacenamiento de energía en respaldo eléctrico, sistemas solares pequeños, alarmas, iluminación y aplicaciones donde se requiere almacenamiento confiable.'),
('bateria-solar-leoch-agm-12v-33ah', '<h3>Características del producto</h3><p>La Batería solar Leoch AGM 12V 33Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para respaldo eléctrico, sistemas solares pequeños, alarmas, iluminación y aplicaciones donde se requiere almacenamiento confiable.</p><ul><li>Marca: Leoch</li><li>Tecnología: AGM</li><li>Voltaje: 12V</li><li>Capacidad nominal: 33Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch AGM 12V 33Ah para almacenamiento de energía en respaldo eléctrico, sistemas solares pequeños, alarmas, iluminación y aplicaciones donde se requiere almacenamiento confiable.'),
('bateria-solar-leoch-agm-12v-65ah', '<h3>Características del producto</h3><p>La Batería solar Leoch AGM 12V 65Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para respaldo eléctrico, sistemas solares pequeños, alarmas, iluminación y aplicaciones donde se requiere almacenamiento confiable.</p><ul><li>Marca: Leoch</li><li>Tecnología: AGM</li><li>Voltaje: 12V</li><li>Capacidad nominal: 65Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch AGM 12V 65Ah para almacenamiento de energía en respaldo eléctrico, sistemas solares pequeños, alarmas, iluminación y aplicaciones donde se requiere almacenamiento confiable.'),
('bateria-solar-leoch-gel-12v-50ah', '<h3>Características del producto</h3><p>La Batería solar Leoch GEL 12V 50Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para sistemas solares con ciclos de carga y descarga, respaldo domiciliario y soluciones de almacenamiento para energía renovable.</p><ul><li>Marca: Leoch</li><li>Tecnología: GEL</li><li>Voltaje: 12V</li><li>Capacidad nominal: 50Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch GEL 12V 50Ah para almacenamiento de energía en sistemas solares con ciclos de carga y descarga, respaldo domiciliario y soluciones de almacenamiento para energía renovable.'),
('bateria-solar-leoch-gel-12v-100ah', '<h3>Características del producto</h3><p>La Batería solar Leoch GEL 12V 100Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para sistemas solares con ciclos de carga y descarga, respaldo domiciliario y soluciones de almacenamiento para energía renovable.</p><ul><li>Marca: Leoch</li><li>Tecnología: GEL</li><li>Voltaje: 12V</li><li>Capacidad nominal: 100Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch GEL 12V 100Ah para almacenamiento de energía en sistemas solares con ciclos de carga y descarga, respaldo domiciliario y soluciones de almacenamiento para energía renovable.'),
('bateria-solar-leoch-gel-12v-150ah', '<h3>Características del producto</h3><p>La Batería solar Leoch GEL 12V 150Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para sistemas solares con ciclos de carga y descarga, respaldo domiciliario y soluciones de almacenamiento para energía renovable.</p><ul><li>Marca: Leoch</li><li>Tecnología: GEL</li><li>Voltaje: 12V</li><li>Capacidad nominal: 150Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch GEL 12V 150Ah para almacenamiento de energía en sistemas solares con ciclos de carga y descarga, respaldo domiciliario y soluciones de almacenamiento para energía renovable.'),
('bateria-solar-leoch-gel-12v-200ah', '<h3>Características del producto</h3><p>La Batería solar Leoch GEL 12V 200Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para sistemas solares con ciclos de carga y descarga, respaldo domiciliario y soluciones de almacenamiento para energía renovable.</p><ul><li>Marca: Leoch</li><li>Tecnología: GEL</li><li>Voltaje: 12V</li><li>Capacidad nominal: 200Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch GEL 12V 200Ah para almacenamiento de energía en sistemas solares con ciclos de carga y descarga, respaldo domiciliario y soluciones de almacenamiento para energía renovable.'),
('bateria-solar-leoch-gel-12v-250ah', '<h3>Características del producto</h3><p>La Batería solar Leoch GEL 12V 250Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para sistemas solares con ciclos de carga y descarga, respaldo domiciliario y soluciones de almacenamiento para energía renovable.</p><ul><li>Marca: Leoch</li><li>Tecnología: GEL</li><li>Voltaje: 12V</li><li>Capacidad nominal: 250Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch GEL 12V 250Ah para almacenamiento de energía en sistemas solares con ciclos de carga y descarga, respaldo domiciliario y soluciones de almacenamiento para energía renovable.'),
('bateria-solar-leoch-de-litio-12v-100ah', '<h3>Características del producto</h3><p>La Batería solar Leoch de litio 12V 100Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para sistemas solares compactos, respaldo energético y aplicaciones que requieren capacidad y voltaje adecuados para el sistema.</p><ul><li>Marca: Leoch</li><li>Tecnología: litio</li><li>Voltaje: 12V</li><li>Capacidad nominal: 100Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch de litio 12V 100Ah para almacenamiento de energía en sistemas solares compactos, respaldo energético y aplicaciones que requieren capacidad y voltaje adecuados para el sistema.'),
('bateria-solar-leoch-de-litio-12v-150ah', '<h3>Características del producto</h3><p>La Batería solar Leoch de litio 12V 150Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para sistemas solares compactos, respaldo energético y aplicaciones que requieren capacidad y voltaje adecuados para el sistema.</p><ul><li>Marca: Leoch</li><li>Tecnología: litio</li><li>Voltaje: 12V</li><li>Capacidad nominal: 150Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch de litio 12V 150Ah para almacenamiento de energía en sistemas solares compactos, respaldo energético y aplicaciones que requieren capacidad y voltaje adecuados para el sistema.'),
('bateria-solar-leoch-de-litio-12v-200ah', '<h3>Características del producto</h3><p>La Batería solar Leoch de litio 12V 200Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para sistemas solares compactos, respaldo energético y aplicaciones que requieren capacidad y voltaje adecuados para el sistema.</p><ul><li>Marca: Leoch</li><li>Tecnología: litio</li><li>Voltaje: 12V</li><li>Capacidad nominal: 200Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch de litio 12V 200Ah para almacenamiento de energía en sistemas solares compactos, respaldo energético y aplicaciones que requieren capacidad y voltaje adecuados para el sistema.'),
('bateria-solar-leoch-de-litio-24v-100ah', '<h3>Características del producto</h3><p>La Batería solar Leoch de litio 24V 100Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para instalaciones solares medianas, respaldo energético y sistemas que buscan capacidad acorde con los requerimientos del sistema.</p><ul><li>Marca: Leoch</li><li>Tecnología: litio</li><li>Voltaje: 24V</li><li>Capacidad nominal: 100Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch de litio 24V 100Ah para almacenamiento de energía en instalaciones solares medianas, respaldo energético y sistemas que buscan capacidad acorde con los requerimientos del sistema.'),
('bateria-solar-leoch-de-litio-24v-150ah', '<h3>Características del producto</h3><p>La Batería solar Leoch de litio 24V 150Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para instalaciones solares medianas, respaldo energético y sistemas que buscan capacidad acorde con los requerimientos del sistema.</p><ul><li>Marca: Leoch</li><li>Tecnología: litio</li><li>Voltaje: 24V</li><li>Capacidad nominal: 150Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch de litio 24V 150Ah para almacenamiento de energía en instalaciones solares medianas, respaldo energético y sistemas que buscan capacidad acorde con los requerimientos del sistema.'),
('bateria-solar-leoch-de-litio-24v-200ah', '<h3>Características del producto</h3><p>La Batería solar Leoch de litio 24V 200Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para instalaciones solares medianas, respaldo energético y sistemas que buscan capacidad acorde con los requerimientos del sistema.</p><ul><li>Marca: Leoch</li><li>Tecnología: litio</li><li>Voltaje: 24V</li><li>Capacidad nominal: 200Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch de litio 24V 200Ah para almacenamiento de energía en instalaciones solares medianas, respaldo energético y sistemas que buscan capacidad acorde con los requerimientos del sistema.'),
('bateria-solar-leoch-de-litio-48v-100ah', '<h3>Características del producto</h3><p>La Batería solar Leoch de litio 48V 100Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para sistemas solares de alto rendimiento, bancos de energía de mayor capacidad y proyectos que requieren capacidad adecuada para el proyecto.</p><ul><li>Marca: Leoch</li><li>Tecnología: litio</li><li>Voltaje: 48V</li><li>Capacidad nominal: 100Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch de litio 48V 100Ah para almacenamiento de energía en sistemas solares de alto rendimiento, bancos de energía de mayor capacidad y proyectos que requieren capacidad adecuada para el proyecto.'),
('bateria-solar-leoch-de-litio-48v-150ah', '<h3>Características del producto</h3><p>La Batería solar Leoch de litio 48V 150Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para sistemas solares de alto rendimiento, bancos de energía de mayor capacidad y proyectos que requieren capacidad adecuada para el proyecto.</p><ul><li>Marca: Leoch</li><li>Tecnología: litio</li><li>Voltaje: 48V</li><li>Capacidad nominal: 150Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch de litio 48V 150Ah para almacenamiento de energía en sistemas solares de alto rendimiento, bancos de energía de mayor capacidad y proyectos que requieren capacidad adecuada para el proyecto.'),
('bateria-solar-leoch-de-litio-48v-200ah', '<h3>Características del producto</h3><p>La Batería solar Leoch de litio 48V 200Ah permite almacenar energía para sistemas solares, respaldo eléctrico y soluciones de autonomía energética.</p><p>Es una alternativa recomendada para sistemas solares de alto rendimiento, bancos de energía de mayor capacidad y proyectos que requieren capacidad adecuada para el proyecto.</p><ul><li>Marca: Leoch</li><li>Tecnología: litio</li><li>Voltaje: 48V</li><li>Capacidad nominal: 200Ah</li><li>Aplicación: almacenamiento de energía solar y respaldo eléctrico</li></ul><p>Antes de elegir una batería solar, es importante calcular el consumo, el tiempo de autonomía requerido y el tipo de sistema donde será instalada.</p><p>Novatec Energy brinda asesoría para seleccionar la batería adecuada según cada proyecto.</p>', 'Batería solar Leoch de litio 48V 200Ah para almacenamiento de energía en sistemas solares de alto rendimiento, bancos de energía de mayor capacidad y proyectos que requieren capacidad adecuada para el proyecto.');

UPDATE `productos` p
INNER JOIN `_import_descripciones_seo_novatec` t ON t.`slug` = p.`slug`
SET
  p.`descripcion` = t.`descripcion`,
  p.`breve_descripcion` = t.`breve_descripcion`;

DROP TEMPORARY TABLE `_import_descripciones_seo_novatec`;

DROP TEMPORARY TABLE `_import_productos_novatec`;

COMMIT;

-- Verificación posterior: deben devolver 5 categorías, 14 subcategorías y 57 productos.
SELECT
  (SELECT COUNT(*) FROM `category`) AS total_categorias,
  (SELECT COUNT(*) FROM `subcategory`) AS total_subcategorias,
  (SELECT COUNT(*) FROM `productos`) AS total_productos;

SELECT
  c.`category`,
  s.`subcategory`,
  COUNT(p.`id`) AS total_productos
FROM `category` c
INNER JOIN `subcategory` s ON s.`id_category` = c.`id`
LEFT JOIN `productos` p ON p.`id_categoria` = c.`id` AND p.`id_subcategory` = s.`id`
GROUP BY c.`id`, s.`id`
ORDER BY c.`category`, s.`subcategory`;
